"""empty message

Revision ID: db21dcdde6a3
Revises: 095a7d1ec968
Create Date: 2020-10-01 23:32:52.546163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db21dcdde6a3'
down_revision = '095a7d1ec968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.drop_column('users', 'name')
    op.drop_column('users', 'company_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_name', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
